blueprint:
  name: Confirmable Notification Automation
  description: >-
    A automation that sends an actionable notification with a confirmation before
    running the specified action.
  domain: automation
  source_url: https://github.com/home-assistant/core/blob/master/homeassistant/components/script/blueprints/confirmable_notification.yaml
  input:
    trigger_sensor:
      name: Trigger
      description: Binary sensor that trigger the alert
      selector:
        entity:
          domain: binary_sensor
    trigger_id:
      name: Trigger Identifier
      description: Unique identifier
      selector:
        text:
    trigger_fortime:
      name: Time on on state before triggering
      description: How long does the sensor has to be triggered before starting the automation
      default: "00:00:00"
      selector:
        time:
    trigger_state:
      name: State of the trigger
      description: State of the trigger (on or off)
      default: 'on'
      selector:
        text:
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      default: false
      selector:
        device:
          integration: mobile_app
    notify_group:
      name: group to notify
      description: group of devices to notify. Need to run the home assistant app 
      default: ""
      selector:
        text:
    notification_channel:
      name: Notificaiton Channel
      description: Channel under which notifications are groupped
      default: "update"
      selector:
        text:  
    title:
      name: "Title"
      description: "The title of the button shown in the notification."
      default: ""
      selector:
        text:
    message:
      name: "Message"
      description: "The message body"
      selector:
        text:
    confirm_text:
      name: "Confirmation Text"
      description: "Text to show on the confirmation button"
      default: "Confirm"
      selector:
        text:
    confirm_action:
      name: "Confirmation Action"
      description: "Action to run when notification is confirmed"
      default: []
      selector:
        action:
    dismiss_text:
      name: "Dismiss Text"
      description: "Text to show on the dismiss button"
      default: "Dismiss"
      selector:
        text:
    dismiss_action:
      name: "Dismiss Action"
      description: "Action to run when notification is dismissed"
      default: []
      selector:
        action:

mode: restart

variables:
  trigger_id: !input trigger_id
  action_dismiss: '{{ ''DISMISS_'' ~ trigger_id }}'
  action_confirm: '{{ ''CONFIRM_'' ~ trigger_id }}'
  group_target: !input notify_group

trigger:
  - platform: state
    entity_id: !input trigger_sensor
    to: !input trigger_state
    for: !input trigger_fortime
    id: triggered


action:
  - choose:
    - conditions: "{{ not group_target }}"
      sequence:
      - device_id: !input notify_device
        domain: mobile_app
        type: notify
        message: !input message
        title: !input title
        data:
          actions:
          - action: "{{action_confirm}}"
            title: !input confirm_text
          - action: "{{action_dismiss}}"
            title: !input dismiss_text
    default:
      - service: "notify.{{ group_target }}"
        data:
          message: !input message
          title: !input title
          data:
            ttl: 0
            priority: high
            channel: !input notification_channel
            importance: high
            ledColor: blue
            actions:
            - action: "{{action_confirm}}"
              title: !input confirm_text
            - action: "{{action_dismiss}}"
              title: !input dismiss_text
  - wait_for_trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "{{action_confirm}}"
      id: restart
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "{{action_dismiss}}"
      id: dismiss
    continue_on_timeout: false
    timeout: '7200'
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ wait.trigger.event.data.action == action_confirm }}'
      sequence: !input confirm_action
    - conditions:
      - condition: template
        value_template: '{{ wait.trigger.event.data.action == action_dismiss }}'
      sequence: !input dismiss_action
    default: []

